version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: talent
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"